### ISSUE TITLE
Respect If-Modified-Since in http_access_server.coffee

### ISSUE THREAD

**Issue by edemaine** [vsivsi/meteor-file-collection#108]
Currently, `http_access_server.coffee` sends the requested file independent of any conditionals sent in the HTTP headers (see https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html).  A particularly useful header to respect would be `If-Modified-Since` to prevent resending files that haven't changed.

As I understand it, the modification to `get` would be something like this (between setting `headers` and checking for `range` header):

```
if Date.parse(req.headers['if-modified-since']) >= req.gridFS.uploadDate.getTime()
   res.writeHead 304, headers
   res.end()
   return
```

I haven't tested yet, though, hence no pull request.  Let me know if you'd rather that.

**Comment by vsivsi** [comment]
Good idea. If you put together a solid PR (with passing tests for the new feature, including gracefully handling invalid/malformed headers, etc) I'll merge and release within a day or two. Otherwise it will probably take me weeks to get around to doin something like this myself right now.

**Comment by edemaine** [comment]
Cool, thanks for the quick response!  I'll work on such a pull request.

**Comment by vsivsi** [comment]
Closing this to concentrate any remaining discussion on the open PR
