### ISSUE TITLE
feature request: File Manipulation

### ISSUE THREAD

**Issue by pajooh** [vsivsi/meteor-file-collection#12]
like [CollectionFS](https://github.com/CollectionFS/Meteor-CollectionFS/#file-manipulation), it is very useful to be able to transform files on insert/read/etc.
or at least to have some event hooks to use it for transformations

**Comment by TimoLins** [comment]
Is jobCollection still the best way of doing this? Because it seems like it's flagged on atmosphere and not recommended.

**Comment by vsivsi** [comment]
vsivsi:job-collection is alive and well. https://atmospherejs.com/vsivsi/job-collection

**Comment by vsivsi** [comment]
BTW, I updated the stale links in my initial response above to point to the correct resources.
