### ISSUE TITLE
How to create a downloadable link

### ISSUE THREAD

**Issue by timothyarmes** [vsivsi/meteor-file-collection#123]
Hi,

This question isn't directly related to meteor-fie-collection, but I can think of no better place to ask it since I expect many of you will have had this issue.

I have files store in grids, uploaded using this project. Now I wish to provide a download link:

    <a href="/files/<id>">file</a>

The problem is that as soon as I click on it, FlowRouter takes change and says that there's no route defined. Which is true of course.

How can I force a GET?

**Comment by timothyarmes** [comment]
Ah, found it:

    <a href="/files/<id>" rel="external">file</a>

**Comment by vsivsi** [comment]
Ya, it's not intuitive, just one of those things you gotta know.
