### ISSUE TITLE
how can we set Resumable's header ?

### ISSUE THREAD

**Issue by crapthings** [vsivsi/meteor-file-collection#130]
i've set these code before resumable.upload(), but there's nothing in req.headers

Documents.resumable.defaults.headers = {
      'x-auth-token': Accounts._storedLoginToken()
    }

Documents.resumable.withCredentials = true

**Comment by vsivsi** [comment]
To customize resumable, you need to create your own resumable instance, rather than using the one automatically provided on the client.

It's easy, just use the code for the default implementation as a reference: https://github.com/vsivsi/meteor-file-collection/blob/master/src/resumable_client.coffee#L28-L46

**Comment by crapthings** [comment]
i can find key, but there's no value found in req.headers

    'access-control-request-headers': 'origin, content-type, x-cube-token, x-auth-token',

it's working on desktop browser

not work with cordova preflight

**Comment by crapthings** [comment]
after add

    'Access-Control-Allow-Headers': 'x-auth-token, user-agent, x-cube-token',

it works

but the if i remove x-cube-token(a custom header)

i can't get x-auth-token too, its weird

'Access-Control-Allow-Headers': 'x-auth-token, user-agent',

**Comment by crapthings** [comment]
now everything works fine!!!

**Comment by fengyibo** [comment]
@crapthings your reply is so helpfull,
could you tell me how to make that works fine.
we handle auth  with cordova  but handle_auth always return null

`handle_auth = (req, res, next) ->
      unless req.meteorUserId?
         # Lookup userId if token is provided in HTTP heder
         if req.headers?['x-auth-token']?
            req.meteorUserId = lookup_userId_by_token req.headers['x-auth-token']
         # Or as a URL query of the same name
         else if req.cookies?['X-Auth-Token']?
            req.meteorUserId = lookup_userId_by_token req.cookies['X-Auth-Token']
         else
            req.meteorUserId = null`

**Comment by crapthings** [comment]
等我有电脑的

**Comment by fengyibo** [comment]
@crapthings  谢谢啊，路过济南或者上海我请客

**Comment by fengyibo** [comment]
@crapthings 

`Documents.resumable.defaults.headers = {
'x-auth-token': Accounts._storedLoginToken()
}`
'Access-Control-Allow-Headers': 'x-auth-token, user-agent',
http post 方法可以正常获取 x-auth-token，cordova 下http options 还是取不到 x-auth-token，貌似resumable.defaults.headers 没有影响到 options 方法，或者是因为options方法是由浏览器出发的，所有使用的不是 resumable的header？？？
求教！

**Comment by crapthings** [comment]
Documents.resumable

这下边有个叫 opt还是opts 的对象，实际在这里写

Documents.resumable.opt.headers = { test: 1 }

后边就能抓到了

**Comment by fengyibo** [comment]
用了opts的设置，post 时可以抓到，options还是不行，估计是因为options是浏览器触发的原因吧

**Comment by crapthings** [comment]
@fengyibo 

https://github.com/crapthings/meteor-cordova-file-upload/blob/master/lib/files.js
