### ISSUE TITLE
Firefox video plays only once

### ISSUE THREAD

**Issue by ignl** [vsivsi/meteor-file-collection#135]
Hi, when I upload videos to gridfs and then try to use them in firefox it plays fine, but only once (also unable to use seeker). Chrome plays fine but first time it plays seeker is hidden and it shows that video is "live". Is that's how it works now or I am doing something wrong? My config is pretty close to the one in documentation.

**Comment by vsivsi** [comment]
Hi, this package has nothing specifically to do with playing video. It allows you to upload, store, and retrieve files. It supports HTTP range requests, which is what I imagine video players use to implement seeking. 

I can't provide support for specific use cases like this. If you can identify a bug or missing feature in the file-collection package, I'll be more than happy to try to help, but I don't have the time to debug what is likely a client-side player issue.

**Comment by ignl** [comment]
Hi np I understand that. The reason I asked is because I found ticket #27 by @riaan53 and though he was solving similar problem and just wanted to be sure if I am not missing something (like some parameter or setting). I will investigate more and let you know if I find a problem.

**Comment by ignl** [comment]
Ok so I just checked simple request to video file and response was simple 200 OK. As I understand it should be 206 for partial request? Or I should pass some request parameters for that?

**Comment by vsivsi** [comment]
Hi, you need you make HTTP requests with the required range headers.  You can look at the tests for this functionality for a working example: 
https://github.com/vsivsi/meteor-file-collection/blob/master/test/file_collection_tests.coffee#L667

**Comment by ignl** [comment]
Yes I didn't add range header in my test - it works fine.
It seems this is a problem with recordrtc as after some debugging with chrome network I found that partial requests works fine so I tried different webm file (not the one recorded with recordrtc) and it worked fine. I guess this ticket can be closed.

**Comment by vsivsi** [comment]
Great!
