### ISSUE TITLE
Is there a way to call resumable.addFile()?

### ISSUE THREAD

**Issue by Dubbedge** [vsivsi/meteor-file-collection#138]
I'm not sure I'm asking the right question, but Is there a way to call `resumable.addFile()` within your package? If so, how? I'd like to programmatically upload an image blob (server side). I'll take the needed precautions to make sure safe blobs are getting uploaded, I just want to find out if it is currently possible.

**Comment by Dubbedge** [comment]
Never mind, I figured it out... `NameOfCollection.resumable.addFile(blob)`. So simple.

**Comment by vsivsi** [comment]
Glad you figured it out. For future reference, this was already discussed in this issue as well: https://github.com/vsivsi/meteor-file-collection/issues/36
