### ISSUE TITLE
Loading image on server from URL

### ISSUE THREAD

**Issue by manuscript80** [vsivsi/meteor-file-collection#140]
I haven't been able to find any examples of loading an image from a URL while on the server.  I've seen the recommendations to use a PUT HTTP request, but it seems really wasteful to download the file from a URL and then send it to Resumable.js.  Here's what's I've been trying...

```
Meteor.http.get(media.url, {npmRequestOptions: { encoding: 'base64' }}, function(e, res) {
  var stream = MediaDocs.upsertStream(
      {
         _id: new Meteor.Collection.ObjectID(),
         filename: media.filename,
         contentType: 'image/' + media.extension
      },
      function (err, fileObj) {
         if (err) {
             console.log(err);
         } else {
             console.log("FileObj: ", fileObj);
         }
      }
   );
   stream.end(res.content);
});
```

My console output always shows a length of 765031 for fileObj, regardless of the actual content size.  Should I be using a different encoding?  Or is there a better way to save an image file from the server?

**Comment by vsivsi** [comment]
Hi, rather than use the Meteor HTTP calls, I'd just use the [npm request package](https://www.npmjs.com/package/request#streaming), which will return a readable stream that you can pipe to the result of `fc.upsertStream()`

So something more like the code below will enable you to efficiently handle retrieving large files and writing them into the fileCollection:

```js
var request = require('request');

var stream = MediaDocs.upsertStream(
      {
         _id: new Meteor.Collection.ObjectID(),
         filename: media.filename,
         contentType: 'image/' + media.extension
      },
      function (err, fileObj) {
         if (err) {
             console.log(err);
         } else {
             console.log("FileObj: ", fileObj);
         }
      }
   );

stream.on('finish', function () { /* Perform any actions after write... */);

request(media.url)
   .on('error', function(err) { /* Handle error */ })
   .pipe(stream);
```

**Comment by manuscript80** [comment]
That did the trick, thank you.  What a flexible package!

**Comment by vsivsi** [comment]
Great!
