### ISSUE TITLE
Can't make file get works on mobile

### ISSUE THREAD

**Issue by humbertocruz** [vsivsi/meteor-file-collection#154]
Hello,

My Android cordova app cant read any file on gridfs, it's works on chrome and on the app "Cordova Browser" so I think its a permission issue, but since the route is http://localhost:12568 that wouldn`t be necessary, right ? All the files routes give a 404 error and I am using FlowRouter. Thanks

**Comment by vsivsi** [comment]
Hi, I'm not a mobile/Cordova developer. All support for Cordova in this package has been community contributed. If you haven't already, you should look at the documentation for Cordova and CORS support in file-collection. 

https://github.com/vsivsi/meteor-file-collection#cors--apache-cordova-support

Specifically, you should make a note of the workaround at the bottom of that section:

```
// Required to work around a bug in Cordova?
App.accessRule("blob:*");
```

**Comment by humbertocruz** [comment]
Hello, yes, i tried that but didnt worked. But I made it pointing to another app using the same dabase ( the admin panel for the mobile app ) and it's ok for now, I have other big problem with large files and I will open another issue, thanks
