### ISSUE TITLE
where is my file?

### ISSUE THREAD

**Issue by varunajmera0** [vsivsi/meteor-file-collection#155]
Where is my file?  i uploaded image . how can i see my image?

**Comment by vsivsi** [comment]
If the upload succeeded, the image is stored in a MongoDB gridFS collection.  You can either get a readable stream for the file on the server or you can retrieve it usin HTTP.  

I suggest you start with the sample app:  

https://github.com/vsivsi/meteor-file-sample-app

**Comment by varunajmera0** [comment]
When i upload the image , database will make entry like img name, extension etc..
U want to say img is stored in db. @vsivsi

**Comment by vsivsi** [comment]
Yes the image is stored in the DB. To understand you need to learn about gridFS:

https://docs.mongodb.com/manual/core/gridfs/

I'm happy to answer specific questions about file-collection, but I can't give you a basic tutorial on how the package works. There is a lot of documentation and sample code for you to study. Please do so.
