### ISSUE TITLE
Big files

### ISSUE THREAD

**Issue by humbertocruz** [vsivsi/meteor-file-collection#156]
Hello, I have about 80 images files with +- 600kb in size on a collection. Tried to show it paged on 10/10 but the things got bad. All app acts crazy, not found any record from others collections and the machine getting slow. This end up with meteor freezing with a mongodb task that cant close even with "sudo kill", had to restart the computer.

What is the problem here ? a colection with 80 records can't be so big. This may occur by the browser loading the src of the images from the GET URL ?

I will try a image resize solution on the server side with GM but I havent much time, need to show the app for the client tomorrow :( 

thanks

**Comment by vsivsi** [comment]
Did you solve this problem?  The server side should freeze even with a million files!  I recommend you try out the sample apps if you haven't already. I just verified that there are no obvious performance issues with the latest Meteor version.

**Comment by humbertocruz** [comment]
Hello, yes, but I really do no know what was. I broke the code into peaces and fixed some publications issues. Thanks

**Comment by vsivsi** [comment]
Thanks for replying. Does this issue need to be reopened then? Doen't seem like there is anything more for me to do here.

**Comment by humbertocruz** [comment]
Hello, thanks. You package is amazing and did a very nice job. I can't reproduce that behavior too. I am very woorried about a deadline this week, thanks god all got right fast. I think the problem was about my publications and not about the package it self. Thanks

**Comment by vsivsi** [comment]
Okay, thanks for following up. Best of luck with your project!
