### ISSUE TITLE
How to delete the whole file collection

### ISSUE THREAD

**Issue by dpatte** [vsivsi/meteor-file-collection#162]
I notice that you dont support .remove({})

as per this in your documentation:
"For safety, undefined and empty selectors (undefined, null or {}) are all rejected."

So how would I remove everything? By doing a find({}) and deleting each one individually?
I believe some of my docs may have lock issues in the collection due to a crash, so I want to rebuild the collection from scratch.

Thx

**Comment by vsivsi** [comment]
For cases like this you should just manually remove the three underlying collections from MongoDB directly using e.g. the mongo CLI or another admin tool of your choice. gridFS is just two MingoDB collections `[name].files` and `[name].chunks`. FC also uses a `[name].locks` collection. If you blow these three collections away (or remove all documents from them) then you can start fresh. 

You can also do this within Meteor code by simply opening each of these collections by name as ordinary Meteor collections. Then you can do whatever you want to them. Just don't create gem the first time this way, because each gridFS collection has special indexes that won't get added properly if you manually create the collections. That's why I recommend just dropping the whole collection if you want to start again.

**Comment by dpatte** [comment]
Thanks for the advice. I tried removing them individually but it took 5 seconds each in the loop.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Vaughn Iverson <notifications@github.com> Date: 2017-06-24  13:14  (GMT-05:00) To: vsivsi/meteor-file-collection <meteor-file-collection@noreply.github.com> Cc: David Patte <dpatte@relativedata.com>, Author <author@noreply.github.com> Subject: Re: [vsivsi/meteor-file-collection] How to delete the whole file
  collectino (#162) 
For cases like this you should just manually remove the three underlying collections from MongoDB directly using e.g. the mongo CLI or another admin tool of your choice. gridFS is just two MingoDB collections [name].files and [name].chunks. FC also uses a [name].locks collection. If you blow these three collections away (or remove all documents from them) then you can start fresh.
You can also do this within Meteor code by simply opening each of these collections by name as ordinary Meteor collections. Then you can do whatever you want to them. Just don't create gem the first time this way, because each gridFS collection has special indexes that won't get added properly if you manually create the collections. That's why I recommend just dropping the whole collection if you want to start again.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vsivsi/meteor-file-collection","title":"vsivsi/meteor-file-collection","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/vsivsi/meteor-file-collection"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vsivsi in #162: For cases like this you should just manually remove the three underlying collections from MongoDB directly using e.g. the mongo CLI or another admin tool of your choice. gridFS is just two MingoDB collections `[name].files` and `[name].chunks`. FC also uses a `[name].locks` collection. If you blow these three collections away (or remove all documents from them) then you can start fresh. \r\n\r\nYou can also do this within Meteor code by simply opening each of these collections by name as ordinary Meteor collections. Then you can do whatever you want to them. Just don't create gem the first time this way, because each gridFS collection has special indexes that won't get added properly if you manually create the collections. That's why I recommend just dropping the whole collection if you want to start again. "}],"action":{"name":"View Issue","url":"https://github.com/vsivsi/meteor-file-collection/issues/162#issuecomment-310851544"}}}

**Comment by vsivsi** [comment]
*above comment edited to remove a ton of email header info junk at the bottom of the post*

**Comment by dpatte** [comment]
This worked great for me thank you. Wish there was a way to do this from within Meteor though.
