### ISSUE TITLE
Feature Request: Extend MFC and its Routes to support URL relative paths

### ISSUE THREAD

**Issue by tedgoldstein** [vsivsi/meteor-file-collection#23]
In the system I am building called MedBook, I integrate existing bioinformatic command line  tools  with new meteor-based tools to provides a seamless  analysis environment for researchers and doctors. In bioinformatics, we have many legacy programs that generate collections of files.  It would be good to be able to browse these files in context of other information supplied by Meteor-based code.  Envision a  meteor system which manages experimental data, runs command line tools and ingests the data.

For example,  GSEA is a command line tool from the Broadthat generates a collection of  html files, images, and tab-separated value data files.    It would be great to ingest these files into meteor-gridfs using ether meteor file-collection or collection-fs and be able to support  a web-browsing experience.  The files are organized into directories with relative paths  Typically, there is some distinguished index.html files that is the start file which is in the local "root" directory for the files.  There needs to be a subsystem that first serves up the top index.html page to a web browser. Your /grids/{{_id}} route accomplishes this already.

The browser will load the index.html page. Then the browser will request images and other links which are relative paths to the start page:  /grids/{{_id}}/image1.jpg,   /grids/{{_id}}/image2.jpg  etc. Then when a user clicks a link, <a href="folder1/foo.html">FOO</a> which which  will cause the browser to request   /gridfs/{{_id}}/folder1/foo.html

Fortunately, the browser resolves .. path names.  The page foo.html which has a referee to "../images/image3.jpg" to  issue the request with the eel formed route  " /gridfs/{{_id}}/images/image3.jpg" to request  /gridfs/{{_id}}/images/image3.jpg… etc.     I don't think the existing routes in iron-router would resolve relative path routes.

Of course, the goal is not simply to be a web server implemented on top of meteor. Rather, it would be great for the filter to have an opportunity to have code which inspects the page between gridfs and modify it or add additional information to other page components.  

For example, there could be a Blaze webserver template of the form:

{{webserver gridfs=start_grid_id_helper  filter=filter_helper  width=x height=y}}
	start_grid_id_helper would rerun the _id value for the index.html page
	filter_helper would allow code to insect or modify the page before serving it  

Best regards,
Ted

**Comment by vsivsi** [comment]
Closing this old issue. Feel free to re-open if you still feel that the existing functionality I outlined above doesn't meet your needs.
