### ISSUE TITLE
problems with iron router

### ISSUE THREAD

**Issue by fpaboim** [vsivsi/meteor-file-collection#25]
Hello! I've been trying to get meteor-file-collection to work with iron router but to no avail. I've been able to do a local file upload of a video to the server (I'm converting stuff with ffmpeg then using the localupload to add to gridfs) and after that I want to serve the video. The problem is using the 'path + md5' as a link isn't working and trying to test the link directly leads me to the iron router 404. Should it work out of the box or do I need to do something with iron router server side routes? I read the iron-router documentation for server side routes but it went over my head... The strange thing is the thumbnail still works on the example app with iron-router which makes me think it's something else. Any ideas would be appreciated. Thanks and good job with the package, Francisco.

**Comment by vsivsi** [comment]
Great, glad you solved it!  -V
