### ISSUE TITLE
video playback with gridfs on chrome

### ISSUE THREAD

**Issue by fpaboim** [vsivsi/meteor-file-collection#26]
Seems like chrome is a bit picky with gridfs stored videos. While firefox seems to handle videos well as things are, to allow seeking in chrome it's necessary to add 'Accept-Ranges': 'bytes' to the header. I fixed it in my local copy simply by adding this to the headers variable in http_access_server.coffee:92. 

ref:
http://stackoverflow.com/questions/13346041/html5-audio-from-mongodb-gridfs

Cheers,
Francisco

**Comment by vsivsi** [comment]
@riaan53 Hi, I'm just recently back from vacation. Thanks for this question and for the other work you've done on other topics. I'll start working on these tomorrow. Thanks for your patience!

**Comment by vsivsi** [comment]
@fpaboim  Thanks for submitting this issue!

It looks like the PR @riaan53 submitted should fix this: https://github.com/vsivsi/meteor-file-collection/pull/27

I plan to merge that PR into a new release as soon as I can thoroughly test it out.

**Comment by vsivsi** [comment]
@fpaboim  Just to update status on this... @riaan53 is working on some changes to the underlying gridfs streaming support that we need to fully integrate and test prior to merging in his range request changes. Once all of this is done, it should be a big improvement for video streaming, and other large file handling. We're (mostly @riaan53) working hard to get it right the first time.

**Comment by vsivsi** [comment]
This issue will be resolved when I publish v1.0.0 later today.

**Comment by fpaboim** [comment]
Looks like this was fixed! Working great here, good job ;)

**Comment by vsivsi** [comment]
Great!  Thanks for reporting back.  -V
