### ISSUE TITLE
error: No compatible build found (Windows)

### ISSUE THREAD

**Issue by ganySA** [vsivsi/meteor-file-collection#34]
Hi

When i attempt to add file-collection i get an error: No compatible build found.

I am doing this on Windows Meteor.

**Comment by vsivsi** [comment]
Hi, file-collection has native components that need to be custom built for each platform. The published package is built for the three fully supported Meteor platforms: OSX, Linux64 and Linux32. I am aware of the effort to port Meteor to Windows, but to my knowledge the Atmosphere package system does not yet allow packages with native components to be built for Windows. 

Unfortunately, the native component dependency is the MongoDB/GridFS driver for node.js, which is central to the functioning of file-collection. 

You can try to manually clone the file-collection repo into your apllication's` package` directory, and then edit the `.meteor/packages` file to add `vsivsi:file-collection`. This should cause Meteor to find and locally build file-collection and its necessary native components. This is precisely how new package versions are developed and tested before being published to atmosphere, so it should work.

**Comment by ganySA** [comment]
Thanks for the comprehensive update!

I have attempted your instructions and although i seem to have made good progress in getting the npm modules as you said, the problem i have now is that the build crashes on:

=> Started proxy.
=> Errors prevented startup:

   While building package vsivsi:file-collection:
   error: File not found: resumable/resumable.js

=> Your application has errors. Waiting for file change.

Any idea what this might be?

**Comment by vsivsi** [comment]
Resumable.js is included as a git subproject. When you clone the repo, you need to use the `--recursive` option with git, so it will automatically clone the subprojects as well.

**Comment by ganySA** [comment]
Thanks for all the help. Much appreciated.

**Comment by vsivsi** [comment]
Happy to help...  -V

**Comment by vsivsi** [comment]
@ganySA  Meteor added support for building native package dependencies for Windows today.  Version 1.0.5 of file-collection should work for you. See this issue for more info: https://github.com/vsivsi/meteor-file-collection/issues/35

**Comment by ganySA** [comment]
Vsivsi - thanks for this will try this out now! Thanks a lot for your info on how to resolve this its has helped me on many packages.
