### ISSUE TITLE
Question: Save a canvas image

### ISSUE THREAD

**Issue by ganySA** [vsivsi/meteor-file-collection#36]
Hi

I have a image which i have loaded using a great Javascript Load library (local machine into canvas) and then manipulated using the great cropper library.

I can probably convert the canvas data using toDataURL(), however my question is how could i save this using file collection?

**Comment by vsivsi** [comment]
Hi @ganySA.  You may find the discussion on this issue informative:  https://github.com/vsivsi/meteor-file-collection/issues/29

It basically boils down to creating a File object in the browser from your canvas data, and then handing it off to Resumable, rather than creating a File object from a filesystem file via drag-and-drop or a file dialog. The resumable upload works the same either way. 

Let me know if that helps.

**Comment by vsivsi** [comment]
Adding to above, it looks like a named Blob object is the answer, not a File object. See the answer here: https://github.com/vsivsi/meteor-file-collection/issues/29#issuecomment-70421435

**Comment by ganySA** [comment]
@vsivsi 

Thanks for that link vsi, that post worked great, the file uploads perfectly... i have one final small question.

When i manually add the file i watch the console output window and i am not sure what the additional GET call is that it is making, this doesnt happen in the 'demo':

    var canvas = $('#image-preview').cropper('getCroppedCanvas');
		var dataURL = canvas.toDataURL();
		var myBlob = petFlick.dataURItoBlob(canvas.toDataURL("image/jpeg"));
		myBlob.name = "test.jpeg";
		postImages.resumable.addFile(myBlob);

For some reason i get a 404 because the following GET is made.

    Request URL:http://localhost:3001/gridfs/postImages/_resumable?resumableChunkNumber=1&resumableChunkSize=2097151&resumableCurrentChunkSize=60104&resumableTotalSize=60104&resumableType=image%2Fjpeg&resumableIdentifier=c250588cc88bdea7f6105d5a&resumableFilename=test.jpeg&resumableRelativePath=test.jpeg&resumableTotalChunks=1

Thanks a lot - when i am done i will put together a little sample project to help anyone else, i think the use case of loading a file, manipulating it and then sending it to the server is pretty popular.

**Comment by vsivsi** [comment]
Is that 404 the same as this discussion?   https://github.com/vsivsi/meteor-file-collection/issues/5

**Comment by ganySA** [comment]
perfect its exactly the same. thanks!
