### ISSUE TITLE
Question / Bug: MongoError: duplicate key error

### ISSUE THREAD

**Issue by ganySA** [vsivsi/meteor-file-collection#38]
Hi

I have problem and i am not sure if it is a bug or simply my lack of understanding.

I have my file uploads working 100% using a version of the sample code.

However when i include something such as the below when i render the template (just want to get the count of images) (postImages is my filecollection)

    Template.name.rendered = function(){
          postCount = postImages.find().fetch().count()

          postImages.resumable.on('fileAdded',function(file)
          {
              my code

           }

    };

This causes the following error when i try upload:

    Meteor.makeErrorType.errorClass {error: 409, reason: "MongoError: E11000 duplicate key error index: petf…p key: { : ObjectId('ed7c336a3d08848923b5b801') }", details: undefined, message: "MongoError: E11000 duplicate key error index: petf… { : ObjectId('ed7c336a3d08848923b5b801') } [409]", errorType: "Meteor.Error"…}

    details: undefinederror: 409errorType: "Meteor.Error"message: "MongoError: E11000 duplicate key error index: petflicks.postImages.files.$_id_ dup key: { : ObjectId('ed7c336a3d08848923b5b801') } [409]"reason: "MongoError: E11000 duplicate key error index: petflicks.postImages.files.$_id_ dup key: { : ObjectId('ed7c336a3d08848923b5b801') }"

In fact call that i make to postImages causes this problem. Strangely enough the upload is successful... but the output to the browser console is filled with failed. The resumable callback also fails with an error object, so its hard to know if its a real failure or just this error.

Any ideas...

**Comment by vsivsi** [comment]
Hi.  Duplicate key errors are when you try to insert a document into the collection with the same `_id` value as a document that is already there.  Without seeing your code, it's impossible for me to predict how this might be happening. But it is certainly an insert that is failing.

Have you looked at the sample app?  Its a working photo gallery with automatic thumbnail generation.

**Comment by ganySA** [comment]
Hi vsivsi

I think i have located the problem and i am wondering if there is a way to address it. My code is sitting in the template rendered function. The reason for this is that i have many parameters that i execute in the callback that relate to the template. So every time the template renders it keeps adding events to resumable..... .on .on .on .on etc hence it tries to add the record x times depending on how often the template was rendered.

    Template.mytemplate.rendered = function(){
           postImages.resumable.on('fileAdded', function (file) {
                    //code that relates to the template!
           }   	
           postImages.resumable.on('complete', function (file) {
    	            console.log('Uploaded image');
            }); 
      };

I have looked at resumable but i dont see any apparent way to clear the events... do you know if this is possible....

**Comment by ondreian** [comment]
That depends, does your postImages.resumable object only exist after your resumable instance and associated event handlers have been attached?

If it isn't possible to know that the resumable object is initialized on a rerender, then you'll want some sort of ui flag to let it know that the events have already been attached, because at either rate you do not want to clear the events, you just do not want to reinitialize them.

```coffeescript

# somewhere where this makes sense
postImages.resumable.isInitialized = true

Template.mytemplate.rendered = ->
      # check for existance of resumable object and if you have fully initialized it
      unless postImages.resumable?.isInitialized
          postImages.resumable.on 'fileAdded', (file)->
             console.log "file added."
    
          postImages.resumable.on 'complete', (file)->
             console.log 'Uploaded image'
```

**Comment by ganySA** [comment]
Thanks nice workaround... and i will get my head around it, challenge i have then is i have two sets of upload logic, so will still need to find a way to change the callback function.

But thanks for your help.

**Comment by ganySA** [comment]
Digging about in resumable i see it keeps adding events to

    resumable.events[]

You can see the duplication happen, the array doubles every time i load the template. I will give the following a try (not sure how the internals of resumable will enjoy it)

    resumable.events = []
    //re run my events code

Will let you guys know how it goes.

**Comment by ondreian** [comment]
I would personally advise a wrapper function that is tied to your state then, that away you don't have to work against the resumable internals, but there is nothing wrong with getting in there and understanding how the resumable internals work.

```coffeescript
Template.mytemplate.rendered = ->

      postImages.resumable.on 'fileAdded', (file)->
         return otherFunction(file) if postImages.resumable.override
         defaultHandler(file)
             


```

**Comment by ganySA** [comment]
I just removed it and did some light testing... and it seems to work pretty well.... not sure if there are any other internals that are growing in size... 

Might be a nice one liner in the docs :+1: 

Thanks for the help.

**Comment by ganySA** [comment]
looking good will close this!

**Comment by vsivsi** [comment]
Great, glad you were able to resolve it!

**Comment by YuHuaiChen** [comment]
Very useful! Thanks!!

**Comment by elnzv** [comment]
Having same thing as @ganySA. 
When I upload a file first time, it uploads it and everything is working as expected.
When I remove it and without page refresh add a new one, it uploads it but gives these in console:

```
Exception while simulating the effect of invoking '/fs.files/insert' errorClass {error: 409, reason: "MinimongoError: Duplicate _id '27903baa19f06b6fdcf50275'", details: undefined, message: "MinimongoError: Duplicate _id '27903baa19f06b6fdcf50275' [409]", errorType: "Meteor.Error"} Error: MinimongoError: Duplicate _id '27903baa19f06b6fdcf50275' [409]
    at m.(anonymous function) (http://localhost:3000/packages/allow-deny.js?hash=28b7b02fffd8490f81f75fa9580e532e61473c0a:215:21)
    at http://localhost:3000/packages/ddp-client.js?hash=b5f1b97df6634673c68f37914ae9f4c3231c438e:3957:25
    at withValue (http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:1077:17)
    at Connection.apply (http://localhost:3000/packages/ddp-client.js?hash=b5f1b97df6634673c68f37914ae9f4c3231c438e:3948:54)
    at FileCollection._callMutatorMethod (http://localhost:3000/packages/allow-deny.js?hash=28b7b02fffd8490f81f75fa9580e532e61473c0a:433:29)
    at FileCollection.insert (http://localhost:3000/packages/mongo.js?hash=bc4cc4faf274ce28cefc812067aa65c0d4025ed4:609:25)
    at FileCollection.Mongo.Collection.(anonymous function) [as insert] (http://localhost:3000/packages/aldeed_collection2-core.js?hash=78aa4a4dfcd4f54f1b080164dd6ca648f9f16f75:229:19)
    at FileCollection.insert (http://localhost:3000/packages/vsivsi_file-collection.js?hash=a36fccae6c8212730354b33b3417358e7164218d:1324:46)
    at FileCollection.<anonymous> (http://localhost:3000/packages/matb33_collection-hooks.js?hash=b4fb31946b843c27a27119ed667cdfb53fd1d510:384:19)
    at FileCollection.collection.(anonymous function) [as insert] (http://localhost:3000/packages/matb33_collection-hooks.js?hash=b4fb31946b843c27a27119ed667cdfb53fd1d510:152:21)
manage.js:43 File creation failed! errorClass {error: 409, reason: "MongoError: insertDocument :: caused by :: 11000 E…p key: { : ObjectId('27903baa19f06b6fdcf50275') }", details: undefined, message: "MongoError: insertDocument :: caused by :: 11000 E… { : ObjectId('27903baa19f06b6fdcf50275') } [409]", errorType: "Meteor.Error"}
```

Here is my code:

https://github.com/apinf/api-umbrella-dashboard/blob/3d6c51ed23cfbedbfbb45da1cf4c418ec8be6b68/documentation/manage/client/manage.js

**Comment by vsivsi** [comment]
You insert the new file with key `file.uniqueIdentifier`, but the code attempts to remove it with key `documentationFileId` which appears to come from `documentationFile._str`. And when it attempts to remove the file, there is no error checking to see if the remove call succeeded. My guess is it doesn't, because the wrong `_id` is being used in the remove. 

Presumably, the duplicate key error then arises because the `uniqueIdentifier` value is being reused for the subsequent upload, but the file still exists because the remove silently failed.

Anyway, I don't see any evidence for a bug in file-collection here. Best of luck with your code!

**Comment by brylie** [comment]
Is there a way to pass the `FileCollection.on()` event handler data from the template context? E.g. we want to associate the uploaded file with a related document in a separate collection.

**Comment by brylie** [comment]
Basically, when the file is successfully uploaded, we want to store the file ID in a related document, so that we can access the file when viewing the related page.

**Comment by brylie** [comment]
I have opened support request #120 to ask for clarification, and possibly a documented example, describing how to create a relationship between a FileCollection file document and a document in a separate collection.
