### ISSUE TITLE
how to implement an input file button

### ISSUE THREAD

**Issue by sembrador** [vsivsi/meteor-file-collection#42]
Hi, 

Excelent package!

Excuse me if I seem too silly but I'm wondering how to implement an input file button to choose a file for upload with this package.

HTML
```html
<template name="testform">
    <input type="file" name="image" class="imageFile">
</template>
```
Javascript

```javascript
Template.testform.events({
    submit: function(e, t) {
        e.preventDefault();
        // Submit Code Here...
    },
    "change .imageFile": function(e, t) {
        e.preventDefault();
        // Upload Code Here ???
    }
});
```

Can you give me, please, some sample code to bring me in the right direction.

Regards.

**Comment by vsivsi** [comment]
Hi, something like this should work:

```js
myFiles.resumable.assignBrowse($(".imageFile"));
```

You can find more about this in the [documentation for resumable.js.](http://resumablejs.com)
