### ISSUE TITLE
How can I show error page, for not existing file?

### ISSUE THREAD

**Issue by aclever** [vsivsi/meteor-file-collection#43]
Hello. Hello. Is anybody have tried to show error page if file not exist?
Please give a hint which way to choose)

**Comment by vsivsi** [comment]
Hi, this should be easy.

When you create the job collection on the server, you supply a "lookup" function to create a query for the HTTP GET support you want to set up.  See: https://github.com/vsivsi/meteor-file-collection#configuring-http-methods

This function maps the incoming URL to some file in the file collection:

```js
// GET file data by md5 sum
{ method: 'get',
  path:   '/:_id',
  lookup: function (params, query) {
              return { _id: params._id } } }
``` 

Note, this is a Javascript function, you can do anything in there that your want!  So nothing stops you from adding your own test to see if the requested file exists, and if not, returning a query that will return whatever 404 asset from the file collection you want.  This is very flexible and powerful.

A different way to handle this would be to use Meteor's `HTTP.get()` call on the client to load an asset, and if that fails with a 404, you can redirect to whatever 404 page you would like.  See: http://docs.meteor.com/#/full/http_get

I'm sure there are even more creative ways to handle this, but those two immediately sprang to mind.

Hope that helps.

**Comment by aclever** [comment]
@vsivsi Thanks for help! It's works good for me!

**Comment by vsivsi** [comment]
Great, glad to help.
