### ISSUE TITLE
Not published for windows 

### ISSUE THREAD

**Issue by marmikcfc** [vsivsi/meteor-file-collection#44]
Hi,

Adding the package on windows gives No compatible binary build found for this package error.
Would you please publish this for windows.

Regards

**Comment by vsivsi** [comment]
Hi, version 1.0.5 of file-collection (the latest version) was built for Windows. 

https://github.com/vsivsi/meteor-file-collection/issues/35
https://github.com/vsivsi/meteor-file-collection/issues/34

If this version of file-collection is not working for you on Windows, please respond with the version of Windows, Meteor, etc that you are having issues with, and precise steps to reproduce the error. 

Thanks.

**Comment by vsivsi** [comment]
Just to add...  If you run:
```sh
meteor show vsivsi:file-collection@1.0.5 --ejson
```
You should see:
```json
{                                             
  "exports": [
    {
      "name": "FileCollection",
      "architectures": [
        "server",
        "web.browser",
        "web.cordova"
      ]
    }
  ],
  "implies": [],
  "dependencies": [
    {
      "name": "coffeescript",
      "constraint": "1.0.6",
      "weak": false
    },
    {
      "name": "mongo",
      "constraint": "1.1.0",
      "weak": false
    },
    {
      "name": "webapp",
      "constraint": "1.2.0",
      "weak": false
    }
  ],
  "name": "vsivsi:file-collection",
  "version": "1.0.5",
  "description": "file-collection is a Meteor.js package that cleanly extends Meteor's Collection metaphor for efficiently dealing with collections of files and their data. File Collections are fully reactive, so if you know how to use Meteor Collections, you already know most of what you need to begin working with this package. It also fully supports HTTP upload and download including support for authentication.",
  "summary": "Collections that efficiently store files using MongoDB GridFS, with built-in HTTP support",
  "git": "https://github.com/vsivsi/meteor-file-collection.git",
  "publishedBy": "vsivsi",
  "publishedOn": {
    "$date": 1427420769608
  },
  "installed": false,
  "architecturesOS": [
    "os.osx.x86_64",
    "os.linux.x86_64",
    "os.linux.x86_32",
    "os.windows.x86_32"
  ]
}
```

Note that `"os.windows.x86_32"` is listed above as one of the architectures this is built for.

**Comment by vsivsi** [comment]
Were you able to resolve this problem?

**Comment by vsivsi** [comment]
I'm closing this. Feel free to reopen if you are still having problems.

**Comment by marmikcfc** [comment]
I'm sorry for replying late. Yea I was able to solve the problem. I had shifted my code from ubuntu to windows to try out meteor on windows. I forgot to update my project due to which it was searching for the previous version of the package.

Thanks a lot!
