### ISSUE TITLE
got 403 error when upload with user logged

### ISSUE THREAD

**Issue by xurwxj** [vsivsi/meteor-file-collection#45]
upload When the user logged in, often get 403 mistakes, even log back in, excuse me, what is going wrong?
```
POST http://127.0.0.1:8000/gridfs/files/_resumable 403 (Forbidden)$.send @ resumable.js:713$.send.doneHandler @ resumable.js:657
resumable.js:713 POST http://127.0.0.1:8000/gridfs/files/_resumable 403 (Forbidden)$.send @ 
```

thanks a lot
victor

**Comment by vsivsi** [comment]
Are you setting a `fc.allow()` "write" rule to give permission to the user?
https://github.com/vsivsi/meteor-file-collection#fcallowoptions

**Comment by xurwxj** [comment]
yeah, i've setted as following:
```
Files.allow({
    // The creator of a file owns it. UserId may be null.
    insert: function(userId, file) {
        // Assign the proper owner when a file is created
        file.metadata = file.metadata || {};
        file.metadata.owner = userId;
        return true;
    },
    // Only owners can remove a file
    remove: function(userId, file) {
        if (user_in_roles(userId, ['admin', 'info_admin'])) {
            return true;
        }
        // Only owners can delete
        return (userId === file.metadata.owner);
    },
    // Only owners can retrieve a file via HTTP GET
    read: function(userId, file) {
        if (file.metadata.thumbOf) {
            return true;
        }
        if (user_in_roles(userId, ['admin', 'data_admin', 'common_user'])) {
            return true;
        }
        return (userId === file.metadata.owner);
    },
    // This rule secures the HTTP REST interfaces' PUT/POST
    // Necessary to support Resumable.js
    write: function(userId, file, fields) {
        // Only owners can upload file data
        return (userId === file.metadata.owner);
    }
});
```

**Comment by vsivsi** [comment]
How are you providing the user's authentication token over HTTP?

**Comment by xurwxj** [comment]
use meteor default account-password account-ui, no custom.

**Comment by vsivsi** [comment]
Yes, but the Meteor login only authenticates the default DDP connection.  HTTP connections to resources that you wish to be secure must also be authenticated by passing a valid token either in a cookie or in the HTTP header.  See: https://github.com/vsivsi/meteor-file-collection#http-authentication

You can see this being done in the sample application here:
https://github.com/vsivsi/meteor-file-sample-app/blob/master/sample.coffee#L66

**Comment by xurwxj** [comment]
```
Tracker.autorun(function() {
    userId = Meteor.userId();
    c_user = Meteor.user();
    Meteor.subscribe('allData', userId);
    Meteor.subscribe('allJobs', userId);
    $.cookie('X-Auth-Token', Accounts._storedLoginToken());
});
```
i've setted in client side.
The 403 error will happen only after open the browser with logging user in automatically. In such situation, any action are useless such as to restart the server or close the browser tabs.

**Comment by vsivsi** [comment]
I'm afraid I don't understand exactly what is happening here from your descriptions.  A 403 error in this situation simply means that your `write` allow rule is not being satisfied for some request. Where that allow rule depends on a `userId` matching, it is essential that a valid authentication token be provided in the HTTP request so the server can securely connect that request to a valid userId.

Suggestion:
Add `console.log()` statements within the `write` allow function you provide so you can see what is happening in that code to not allow certain HTTP POSTs. If you see a `null` userId, it means that the auth token was missing or incorrect.

Beyond that, I would need from you a complete minimal sample application with detailed steps to reproduce the problem. Nothing you've told me so far leads me to believe that this is a bug in file-collection, and without code that I can run myself to reproduce the error, there's not much more that I can do to help you.

**Comment by vsivsi** [comment]
Can you make this problem happen with the sample application? 

https://github.com/vsivsi/meteor-file-sample-app

If you can give me exact steps to cause 403 errors when using the above sample application, then I will be happy to try to reproduce and either fix or explain what is happening.

**Comment by xurwxj** [comment]
yeah, only on development mode will happen.
Server will auto restart when finishing to edit server side code,  then occasionally appear the 403 error.

**Comment by xurwxj** [comment]
403 disappeared for new version on https://github.com/vsivsi/meteor-file-sample-app.
thanks a lot.
victor
