### ISSUE TITLE
UTF-8 filenames are not properly handled in download SaveAs... dialogs

### ISSUE THREAD

**Issue by xurwxj** [vsivsi/meteor-file-collection#48]
there will be garbled words for filename if any words in east asia.

victor

**Comment by vsivsi** [comment]
The file-collection package doesn't modify the filename in any way. The filename completely belongs to the developer/application. Are you seeing this problem with the file-collection sample application?

While I appreciate you reporting issues as you see them, you need to do a little more work to give me detailed steps to reproduce what you are seeing.  I can only guess how this could be happening, and I don't have time to play "20 questions" with users to figure out what's going on for each issue.

Please take the time to put together a proper bug report, with detailed steps to reproduce the error you are seeing, and I will take the time to look into it.

**Comment by xurwxj** [comment]
if filename is 'Nodejs中文指南.pdf';
https://github.com/vsivsi/meteor-file-collection/blob/master/http_access_server.coffee#L184
should change to :
```
var userAgent = (req.headers['user-agent']||'').toLowerCase();
 
if(userAgent.indexOf('msie') >= 0 || userAgent.indexOf('chrome') >= 0) {
    res.setHeader('Content-Disposition', 'attachment; filename=' + encodeURIComponent(filename));
} else if(userAgent.indexOf('firefox') >= 0) {
    res.setHeader('Content-Disposition', 'attachment; filename*="utf8\'\'' + encodeURIComponent(filename)+'"');
} else {
    /* safari and other browsers */
    res.setHeader('Content-Disposition', 'attachment; filename=' + new Buffer(filename).toString('binary'));
}
```
if not change, the filename in download dialog will be garbled.

**Comment by vsivsi** [comment]
Okay, I misunderstood and thought you were referring to the gridFS `filename` attribute stored in MongoDB. Thanks for the additional information. I'll look into this today.

**Comment by vsivsi** [comment]
@xurwxj  Just committed a fix for this based on: http://stackoverflow.com/a/20933751
Thanks for reporting this issue!

**Comment by xurwxj** [comment]
update on v1.0.6?
problem still exist in v1.0.6

victor

**Comment by vsivsi** [comment]
What browser are you using?

**Comment by xurwxj** [comment]
mac 10.10
google chrome Version 42.0.2311.90 (64-bit)

**Comment by vsivsi** [comment]
Just tried it on OSX 10.10 with Chrome 42.0.2311.135 and it works just fine...

**Comment by xurwxj** [comment]
upgrade chrome to 42.0.2311.135 and problem still exist when works fine in firefox and safari, screen shot as following:

![qq20150430-1 2x](https://cloud.githubusercontent.com/assets/683421/7405035/ee3d3faa-ef1e-11e4-85b8-baed16302b9c.png)
![qq20150430-2 2x](https://cloud.githubusercontent.com/assets/683421/7405036/ee49a0e2-ef1e-11e4-90ec-c65670d5c218.png)

**Comment by vsivsi** [comment]
Do you see this problem in Chrome with the sample app?  It works perfectly for me.

![screen shot 2015-04-29 at 7 26 35 pm](https://cloud.githubusercontent.com/assets/428642/7405309/ca7e4344-eea5-11e4-9211-4f02b78cc23d.png)

**Comment by CubetaX** [comment]
> if filename is 'Nodejs中文指南.pdf';
> https://github.com/vsivsi/meteor-file-collection/blob/master/http_access_server.coffee#L184
> should change to :
> 
> ```
> var userAgent = (req.headers['user-agent']||'').toLowerCase();
> 
> if(userAgent.indexOf('msie') >= 0 || userAgent.indexOf('chrome') >= 0) {
>     headers['Content-Disposition'] = 'attachment; filename=' + encodeURIComponent(filename);
> } else if(userAgent.indexOf('firefox') >= 0) {
>     headers['Content-Disposition'] = 'attachment; filename*="utf8\'\'' + encodeURIComponent(filename)+'"';
> } else {
>     /* safari and other browsers */
>     headers['Content-Disposition'] = 'attachment; filename=' + new Buffer(filename).toString('binary');
> }
> ```
> if not change, the filename in download dialog will be garbled.

I dont know why safari setting must be a binary..
