### ISSUE TITLE
Error 404 messages on client when uploading a file

### ISSUE THREAD

**Issue by renarl** [vsivsi/meteor-file-collection#5]
When I upload a file in the sampleApp, I get the following error message in the console:

```
http://localhost:3000/gridfs/fs/_resumable?resumableChunkNumber=1&resumableChunkSize=2097152&resumableCurrentChunkSize=103695&resumableTotalSize=103695&resumableType=image%2Fjpeg&resumableIdentifier=af3467014a32bac0528a1946&resumableFilename=test.jpg&resumableRelativePath=test.jpg
Failed to load resource: the server responded with a status of 404 (Not Found)
```

It seems that afterwords everything works just fine, i.e., the uploaded image is shown in the preview field.

Any ideas why the error occurs?

**Comment by vsivsi** [comment]
FWIW, I've successfully made the 404s go away in version 1.1.0, due for release very soon.  204s work just as well, and don't generate the distracting console noise.
