### ISSUE TITLE
GET http://localhost:3000/gridfs/fs/_resumable 404 (Not Found)

### ISSUE THREAD

**Issue by ManuelDeLeon** [vsivsi/meteor-file-collection#51]
I'm trying to reproduce your example app (https://github.com/vsivsi/meteor-file-sample-app) but I get the following error when I drop an image:
```
GET http://localhost:3000/gridfs/fs/_resumable?resumableChunkNumber=1&resumable…ame=blah.jpg&resumableRelativePath=blah.jpg&resumableTotalChunks=1 404 (Not Found)
```

Here's a repro: https://github.com/ManuelDeLeon/file-upload-problem

**Comment by AdamSutch** [comment]
This is normal, it's in the documentation. 
> NOTE: when using Resumable.js to perform file uploads, it is normal to see 404 errors in the client console that look something like: 
> Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/gridfs/fs/_resumable?resumableChunkNumber=1&  ...

See here for details: https://github.com/vsivsi/meteor-file-collection/issues/5

**Comment by ManuelDeLeon** [comment]
Thanks for the quick response Adam, I would have banged my head against the wall the whole weekend.

**Comment by vsivsi** [comment]
@AdamSutch  Thanks for responding to this!  I'm thinking about just emitting a message in the client console explaining the 404s and pointing to the documentation. This question comes up so often...

**Comment by AdamSutch** [comment]
The console log would be a good debug option.
Off by default similar to https://github.com/aldeed/meteor-simple-schema/#debug-mode

**Comment by vsivsi** [comment]
Actually, it looks like these errors can be silenced by using 204 responses instead of 404s.  I'm going to look into doing this   While I'm at it, I'm not sure why resumable.js doesn't do a more efficient HEAD request instead of a GET...

**Comment by vsivsi** [comment]
FWIW, I've successfully made the 404s go away in version 1.1.0, due for release very soon.  204s work just as well, and don't generate the distracting console noise.
