### ISSUE TITLE
"Cannot read property 'master' of undefined" on Modulus

### ISSUE THREAD

**Issue by hellogerard** [vsivsi/meteor-file-collection#52]
Hello,

Here is a puzzler. Using the latest `file-collection` package and the `accounts-base` package (not a real-life example, but produces the error and trying to keep things simple), my app runs fine on my Mac, but when deployed to Modulus, crashes on startup with the following error:

```
TypeError: Cannot read property 'master' of undefined
    at Object.Future.wait (/mnt/app/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:98:1)
    at packages/accounts-base/accounts_common.js:141:1
    at /mnt/app/programs/server/packages/accounts-base.js:243:4
    at /mnt/app/programs/server/packages/accounts-base.js:1659:3
    at /mnt/app/programs/server/boot.js:222:10
    - - - - -
    at packages/mongo/mongo_driver.js:183:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
```

I believe the error has something to do with the fact that `file-collection` uses a different mongodb driver version (2.0.28) from meteor's mongodb driver (1.4.32?).

The weird thing is this only occurs with the `accounts-base` package, on Modulus. Remove it and everything seems to work fine. Run it locally, and it works fine. To reproduce:

1. `meteor create myapp`
1. `cd myapp`
1. `meteor add vsivsi:file-collection accounts-base`
1. `modulus deploy -p myapp` (you have to create `myapp` with a database on Modulus - sorry)
1. The app won't start, and you will see the error in the logs

Any ideas? This could be a meteor problem, or a Modulus problem, but this seemed the best place to look for help. This error is preventing me from upgrading `file-collection`. Happy to help in any way I can.

**Comment by hellogerard** [comment]
Ok, forget the `accounts-base` angle. Not sure why I thought that. It occurs whenever you attempt to connect to Mongo at all. So to reproduce this way:

1. `meteor create myapp`
1. `cd myapp`
1. `meteor add vsivsi:file-collection`
1. Edit `myapp.js` and add `var Players = new Meteor.Collection("players");` in the server section.
1. `modulus deploy -p myapp` (you have to create `myapp` with a database on Modulus - sorry)
1. The app won't start, and you will see the error in the logs

**Comment by hellogerard** [comment]
Sorry for the barrage... More info:

I believe the problem is with Modulus' `demeteorizer` command. It's somehow losing Meteor's version of the mongodb driver and using `file-collection`'s newer version. That gets sent up, and when the app starts, it throws that error which looks like a backwards-compatibility issue.

**Comment by vsivsi** [comment]
Hi, hmm.  Meteor and file-collection definitely use different versions of the mongo driver.  The reason is that file-collection uses the node.js 0.10 "Streams2" interface for proper flow control while moving data in and out of gridFS. Only the mongodb 2.x driver supports Stream2 streams. For their own reasons Meteor is sticking with mongo 1.4.x for now. 

This is changed in file-collection between 0.3 and 1.0 if I recall correctly, so yes, if you are just making that upgrade now, that would explain why you are seeing the issue now.  

I don't really know what's going on in demeteorizer...  Are you explicitly including the meteor 'mongo' package in your packages file?  Just a shot in the dark.  I'm busy this weekend and can't look into this until Monday, but I'm happy to help if you can't figure it out before then.

**Comment by hellogerard** [comment]
No problem! I'm busy this weekend as well, and there's no urgency. Sorry to add another item to your mental checklist. 

Yes, this is definitely more of a problem with demeteorizer than file-collection. 

If you take my example above and run 'meteor build' on it, you can find both versions of mongodb in module sundial feed. If you look at the demeteorized output, there's only one that makes it, in a top-level node_modules folder. 

You can see the issue I've opened over there so I plan to track this over there more closely this week.

**Comment by Soulou** [comment]
Hi there, any news about this issue?

**Comment by vsivsi** [comment]
This issue has been traced to demeteorizer.  You can follow the issue over there: https://github.com/onmodulus/demeteorizer/issues/125

**Comment by hellogerard** [comment]
@vsivsi This is now fixed in the latest version (5.0.0) of the modulus CLI!

**Comment by vsivsi** [comment]
I don't know because I don't use modulus.  It sounds like it should be fixed, assuming the demeteorizer issue was the only hold-up, but I don't have the time to test this out right now.

**Comment by vsivsi** [comment]
@hellogerard  Oops, I mis-read your post above as a question...  Can you personally verify that this is fixed regarding file-collection on modulus using the new demeteorizer?  If so, I'll close this issue.

**Comment by hellogerard** [comment]
@vsivsi Yes, verified. The reproduction I posted above works now on Modulus.

**Comment by vsivsi** [comment]
Great, thanks!
