### ISSUE TITLE
c++ bson extension failed load

### ISSUE THREAD

**Issue by xurwxj** [vsivsi/meteor-file-collection#53]
after upgrade to 1.1.0, get following error:
```
App 21154 stdout: [Error: /home/3dker/web/programs/server/npm/vsivsi_file-collection/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node: invalid ELF header]
App 21154 stderr: js-bson: Failed to load c++ bson extension, using pure JS version
```
env:
ubuntu 14.04
g++

**Comment by xurwxj** [comment]
after google, solved through:
```
npm install -g node-gyp 
cd /home/3dker/web/programs/server/npm/vsivsi_file-collection/node_modules/mongodb/node_modules/mongodb-core/node_modules/
npm uninstall bson
npm install bson
```

**Comment by vsivsi** [comment]
Did you get this error using a local clone of file-collection or using the package from Atmosphere?

**Comment by xurwxj** [comment]
package from atomsphere

**Comment by vsivsi** [comment]
Hmm, that's strange because the platform specific packages on atmosphere should have the binary components (including the bson package) already built.  I haven't seen any sign of this issue in my testing  can you recreate it by downgrading and upgrading again?

**Comment by xurwxj** [comment]
if node downgraded to 0.10, everything sames go normal.

**Comment by vsivsi** [comment]
I see. I'm pretty sure that Meteor doesn't support node 0.12 yet so this makes sense.
