### ISSUE TITLE
Compatibility with Simple Schema / Collection 2 / Autoform

### ISSUE THREAD

**Issue by pcooney10** [vsivsi/meteor-file-collection#74]
Hey, I've been using this package the past couple weeks and really like it so far.

I usually use (simple-schema)[https://github.com/aldeed/meteor-simple-schema] when defining my collections, but ran into some issues when trying to use it in conjunction with `meteor-file-collection`.  Initially it was not a big issue, but I would like to use  (autoform)[https://github.com/aldeed/meteor-autoform] to populate some metadata.

To be more specific, I get `Error: [Unrecognized deny rule type 'update'.]` when trying to attach a schema to a FileCollection collection. Has anyone else come across this? Thanks.

**Comment by vsivsi** [comment]
If you create a normal Meteor collection (or a Collection2 collection) called "<fcName>.files" where '<fcName>' is the name of your file-collection, then it should work like a normal Meteor collection in terms of compatibility with the packages you mention (and in every other way as well).  However, you must be VERY CAREFUL not to mess with the gridFS reserved attributes (see: https://github.com/vsivsi/meteor-file-collection#use), or you almost certainly WILL lose data.

**Comment by pcooney10** [comment]
Hi vsivsi,

Thanks for your quick response.  I *think* I am following what you are saying, but I am still getting erros.  It's probably easiest to walk you through my code, so please see below:

    // setting up initial collection - works perfectly fine
    logos = new FileCollection('logos',
      { resumable: true,   // Enable built-in resumable.js upload support
        http: [
          { method: 'get',
            path: '/md5/:md5',  // this will be at route "/gridfs/logos/mdf/:md5"
            lookup: function (params, query) {  // uses express style url params
              return { md5: params.md5 };       // a query mapping url to documents
            }
          }
        ]
      }
    );
    
    var Schemas = {};
    
    // attempts at defining the '[name]'.files collection
    logos = new Mongo.Collection('logos.files');
        // Error: A method named '/logos.files/insert' is already defined
    logos.files = new Mongo.Collection('logos.files'); 
        // Error: A method named '/logos.files/insert' is already defined
    
    // defining the metadata object
    Schemas.logofiles = new SimpleSchema({
      metadata: {
        type: Object,
        optional: true
      },
      "metadata.company": {
        type: Object,
        optional: true
      },
      "metadata.company._id": {
        type: String,
        label: "Company id",
        optional: true
      },
      "metadata.company.name": {
        type: String,
        label: "Company Name",
        optional: true
      }
    });
    
    // attempts to attach the schema to the collection
    logos.attachSchema(Schemas.logofiles); 
        // Error: [Unrecognized deny rule type 'update'.]
    'logos.files'.attachSchema(Schemas.logofiles); 
        // TypeError: Object logos.files has no method  'attachSchema'
    logos.files.attachSchema(Schemas.logofiles); 
        // TypeError: Cannot call method 'attachSchema' of undefined

I am not sure what I am missing, but any help would be greatly appreciated.

**Comment by vsivsi** [comment]
Okay, scratch that, I thought it might work, but file-collection actually creates a meteor collection named 'logos.files' under the hood, so you are colliding with it.  The issue you are running into is that a file-collection isn't a normal collection. It is a locking gridFS collection, which is actually backed by three mongoDB collections that have very specific schema definitions and access requirements that Meteor (and autoform/Collection2/etc) no nothing about.  And this includes different access rules implemented as different types of allow/deny rules and collection methods that create data safe access mechanisms for the underlying file data. I don't think what you are trying to do is going to work without changes to the other packages, because gridFS is what it is...

**Comment by pcooney10** [comment]
Ah ok i see.  The schema defintion I have for `metadata` seems to jive with the definition required by Meteor / gridFS, so I guess I just need to figure out the access requirments.

The docs says we should have free reign with the `metadata` field, but I think the access controls there might be off.  It seems we are able to set them on insert, but any updates are denied.  (I see this making sense for `_id`, `length`, `chunkSize`, `uploadDate`, and `md5`, but not sure why the same is true for `metadata` [(ref)](https://github.com/vsivsi/meteor-file-collection#use)).

When I try and update the document with mongol / meteor toys, it creates a duplicate record without any image/file data (that upload processing hangs at 0%, and the thumbnail is blank).

I am also trying to update the documents via the mongo shell, but keep getting a syntax error (not sure why, but still working at it).

**Comment by pcooney10** [comment]
At the end of the day all I'd like to do is edit the metadata of the documents (with or without autoform), but I think I may need to create a separate colleciton that contains references to the documents in `fs.files`.

**Comment by vsivsi** [comment]
Are you trying to call fc.update() on the server or client?  As with normal Meteor collections, there are no restrictions on the server using update to modify "non-protected" attributes, like metadata.  The client, however, is not allowed to update the server state at all. This is for safety, because the client is untrusted, and modification of the file record can cause data loss and corruption of the gridFS data structures. If you want the client to modify a file record, you need to write a Meteor method for it to invoke to make that change.

**Comment by vsivsi** [comment]
FYI, You can find the rules that get applied server-side to decide if an update is "safe" here:
https://github.com/vsivsi/meteor-file-collection/blob/master/src/gridFS.coffee#L27

**Comment by pcooney10** [comment]
Ah ok thank you.  I think initially I was trying to push an update that had the original `_id` field and value in the `{$set: object}` function.  

For anyone else who may be interested, I was able to find a solution by doing something like [this](https://github.com/aldeed/meteor-autoform#non-collection-forms) and calling a server side method to push the update to the actual fs collection.  I didn't want to have two collections for the same, so this seems like the best approach.

@vsivsi, thank you for your quick responses

**Comment by vsivsi** [comment]
Great!
