### ISSUE TITLE
CORS/Cordova support

### ISSUE THREAD

**Issue by vsivsi** [vsivsi/meteor-file-collection#79]
@dnish

For some reason, when I merged your remote branch in my git client, the PR you submitted (and all of the comments on it) disappeared from Github!   So let's use this issue for further discussion.

In the end I didn't end up using your modifications, and instead I've implemented what I hope will be a mechanism to enable (optional) CORS support in a much more general/flexible way compared to just allowing `http://meteor.local`

The chages are committed to the `dev` branch now, and you can look at the associated docs in the README:   https://github.com/vsivsi/meteor-file-collection/tree/dev#cors--apache-cordova-support

I hope to release a new version of file-collection on Friday, so please take a look at this and give me your feedback before then if possible.

**Comment by dnish** [comment]
@vsivsi We've switched over to React Native and handle file uploads now via a totalJS app, so we didn't tried a Meteor solution again.

Is the OPT request not needed in <code>Access-Control-Allow-Methods</code>?

**Comment by vsivsi** [comment]
@riaan53   This is probably of interest to you as well...

**Comment by riaan53** [comment]
This looks great! Will try it out.

Thank you for the great work as allways :)

On Tuesday, 19 January 2016, Vaughn Iverson <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> @riaan53 <https://github.com/riaan53> This is probably of interest to you
> as well...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vsivsi/meteor-file-collection/issues/79#issuecomment-172956306>
> .
>


-- 
Riaan Jacobs
riaan53@gmail.com

**Comment by vsivsi** [comment]
I'd like to publish 1.3.0 today or tomorrow.  Last chance for comments on the proposed changes!

**Comment by vsivsi** [comment]
1.3.0 Published on Atmosphere now.
