### ISSUE TITLE
403 on attempted file upload

### ISSUE THREAD

**Issue by jdmswong** [vsivsi/meteor-file-collection#87]
Hi @vsivsi, love the package so far.  The sample app works great and I have been porting some parts over to my production application.  However when I drag a file to upload the console returns:
```
 https://my.url/gridfs/fs/_resumable?resumableChunkNumber=1&resu…ativePath=testfile.jpg&resumableTotalChunks=1 403 

resumable.js:648 
```

followed by a number of:
```
POST https://my.url/gridfs/fs/_resumable 403 (Forbidden)

resumable.js:766 
```
errors on the client.

Haven't found anybody else with this problem, however I have known Iron Router to hijack all client routes, and may be interfering with this.  Can you shed some light on this?

**Comment by vsivsi** [comment]
Without seeing any code its pretty hard to know what is happening.  I've used file-collection with Iron Router, but it probably depends on how they are each configured.

One thing you definitely need to do is create an `fc.allow` rule for 'write' access.  Also, make sure the file is being inserted in the collection before attempting to upload data to it.  Hope that helps.

**Comment by jdmswong** [comment]
It was a misconfigured myData.allow()
